{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glovoapp.gradle",
    "module": "gradle-versioning-plugin",
    "version": "0.1.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glovoapp.gradle",
          "module": "versioning",
          "version": {
            "requires": "0.1.24"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-versioning-plugin-0.1.24.jar",
          "url": "gradle-versioning-plugin-0.1.24.jar",
          "size": 70623,
          "sha512": "abcc3bd85d5b08bc0295be15c7b9db9ce2314812dfccb372a669f04d046b218d09aae326390237609b6233c12991966ee830cae2626a8081d82c562f64bc796b",
          "sha256": "5f355298823c14e051b35feabff432366e66e1fb26604289a96e964f035c1135",
          "sha1": "59aa2f6778bfcab3dc67157f3e6dae9bf6a12ee9",
          "md5": "b3b173034b07966bb03889acc7649f03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glovoapp.gradle",
          "module": "versioning",
          "version": {
            "requires": "0.1.24"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-versioning-plugin-0.1.24.jar",
          "url": "gradle-versioning-plugin-0.1.24.jar",
          "size": 70623,
          "sha512": "abcc3bd85d5b08bc0295be15c7b9db9ce2314812dfccb372a669f04d046b218d09aae326390237609b6233c12991966ee830cae2626a8081d82c562f64bc796b",
          "sha256": "5f355298823c14e051b35feabff432366e66e1fb26604289a96e964f035c1135",
          "sha1": "59aa2f6778bfcab3dc67157f3e6dae9bf6a12ee9",
          "md5": "b3b173034b07966bb03889acc7649f03"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.glovoapp.gradle",
          "module": "gradle-versioning-plugin",
          "version": {
            "requires": "0.1.24"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-versioning-plugin-0.1.24-test-fixtures.jar",
          "url": "gradle-versioning-plugin-0.1.24-test-fixtures.jar",
          "size": 9412,
          "sha512": "47e3a0df64545767178b6fe935d183ff91d49797d9c8df30ae77fef83b314cb5a9ff3dcc10bd7e47f8796bbe428dd5913cdeb886eddc9125e47eda9e232510d5",
          "sha256": "d206dfc093fb99a5b19658a475ff97cfd00274b99052eaa04611fc71890d6224",
          "sha1": "29a8fdbb7c3f3fd47b22a58102ff0898dddc85d1",
          "md5": "aa5b468428bf548f8b29ea502e41972c"
        }
      ],
      "capabilities": [
        {
          "group": "com.glovoapp.gradle",
          "name": "plugin-test-fixtures",
          "version": "0.1.24"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.glovoapp.gradle",
          "module": "gradle-versioning-plugin",
          "version": {
            "requires": "0.1.24"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-versioning-plugin-0.1.24-test-fixtures.jar",
          "url": "gradle-versioning-plugin-0.1.24-test-fixtures.jar",
          "size": 9412,
          "sha512": "47e3a0df64545767178b6fe935d183ff91d49797d9c8df30ae77fef83b314cb5a9ff3dcc10bd7e47f8796bbe428dd5913cdeb886eddc9125e47eda9e232510d5",
          "sha256": "d206dfc093fb99a5b19658a475ff97cfd00274b99052eaa04611fc71890d6224",
          "sha1": "29a8fdbb7c3f3fd47b22a58102ff0898dddc85d1",
          "md5": "aa5b468428bf548f8b29ea502e41972c"
        }
      ],
      "capabilities": [
        {
          "group": "com.glovoapp.gradle",
          "name": "plugin-test-fixtures",
          "version": "0.1.24"
        }
      ]
    }
  ]
}
