# All Android dependencies come from here. Currently SDK 28
FROM 902311805216.dkr.ecr.eu-west-1.amazonaws.com/jenkins-fargate-agents:jenkins-fargate-base-agents-android-217f0210c06168b96a2219cde8c9bc6250788ab6

USER jenkins

# Disable daemon to avoid any kind of issue during the builds
RUN echo org.gradle.parallel=false >> .gradle/gradle.properties

# Required files for downloading gradle wrapper (removed later)
COPY --chown=jenkins gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.properties
COPY --chown=jenkins gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.jar
COPY --chown=jenkins gradlew gradlew

# This will download the gradlew wrapper directly in the agent
RUN ./gradlew tasks \
    && rm gradlew gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties \
    && rmdir -p gradle/wrapper
