name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # disables shallow clone, required by SonarQube
      - name: Verify branch name
        uses: ./.github/actions/compute-release-type
        if: github.event.pull_request
      - name: Setup JDK11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.sonar/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-cache
      - name: Coverage
        run: ./gradlew -s jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io/
      - name: Build Library
        run: ./gradlew -s :library:build
      - name: Build Gradle Plugin
        run: ./gradlew -s :plugin:build
      - name: Build Gradle Plugin for Android
        run: ./gradlew -s :plugin-android:build
