name: release
on:
  workflow_run:
    workflows:
      - build
    branches:
      - master
    types:
      - completed

jobs:
  Release:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.sonar/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-cache
      - name: Bump version
        run: |
          branch=${GITHUB_REF#refs/heads/}
          if [[ $branch == "major/"* ]]; then type=major; elif [[ $branch == "minor/"* ]]; then type=minor; else type=patch; fi
          ./gradlew incrementSemanticVersion --$type
          echo "VERSION=$(cat version.properties | grep version | cut -d'=' -f2)" >> $GITHUB_ENV
      - name: Tag version
        run: |
          git add version.properties
          git commit -m '[NO-CI] Bump version $VERSION'
          git push
          git tag $VERSION
          git push --tags
      - name: Publish plugin
        run: ./gradlew -Pgradle.publish.key=${{ secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }} -s publishPlugins
