name: release
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  Release:
    runs-on: ubuntu-20.04
    if: ${{ github.event.pull_request.merged == true && !startsWith(github.head_ref, 'no-release/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.sonar/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-cache
      - id: compute-release-type
        name: Compute release type
        uses: ./.github/actions/compute-release-type
      - name: Bump version
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GLOVO_ROBOT_PKG_TOKEN }}
        run: |
          ./gradlew incrementSemanticVersion --${{ steps.compute-release-type.outputs.release-type }}
          VERSION=$(cat version.properties | grep version | cut -d'=' -f2)
          git config user.name \"GlovoRobot\"
          git config user.email "tech.platform@glovoapp.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          git add version.properties
          git commit -m 'Bump version $VERSION'
          git push
          git tag $VERSION
          git push --tags
          echo "::set-output name=version::$(echo $VERSION)"
      - name: Publish plugin
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_KEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew -s publish
      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/build/libs/*,!buildSrc/**"
          tag: ${{ steps.bump-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
